apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cache
  namespace: osoda
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-cache
  template:
    metadata:
      labels:
        app: app-cache
    spec:
      containers:
      - name: memcache
        image: memcached:1.6.8